<?php

return [
    'home' => [
        'sk' => [
            'title' => 'Biliardovňa.sk — Biliardový klub v Bratislave',
            'description' => 'Najväčší biliardový klub v Bratislave. Pyramída, Pool, Šípky, Shuffleboard a skvelá atmosféra. Rezervujte si stôl online.',
            'keywords' => 'biliard, pool, pyramída, šípky, shuffleboard, Bratislava, bar, zábava, turnaje',
            'og:title' => 'Biliardovňa.sk — Biliardový klub v Bratislave',
            'og:description' => 'Najväčší biliardový klub v Bratislave. Pyramída, Pool, Šípky, Shuffleboard a skvelá atmosféra.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/home-sk.jpg',
        ],
        'en' => [
            'title' => 'Biliardovňa.sk — Billiard Club in Bratislava',
            'description' => 'The largest billiard club in Bratislava. Pyramid, Pool, Darts, Shuffleboard and great atmosphere. Book a table online.',
            'keywords' => 'billiard, pool, pyramid, darts, shuffleboard, Bratislava, bar, fun, tournaments',
            'og:title' => 'Biliardovňa.sk — Billiard Club in Bratislava',
            'og:description' => 'The largest billiard club in Bratislava. Pyramid, Pool, Darts, Shuffleboard and great atmosphere.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/home-en.jpg',
        ],
        'ru' => [
            'title' => 'Biliardovňa.sk — Бильярдный клуб в Братиславе',
            'description' => 'Крупнейший бильярдный клуб в Братиславе. Пирамида, Пул, Дартс, Шаффлборд и отличная атмосфера. Забронируйте стол онлайн.',
            'keywords' => 'бильярд, пул, пирамида, дартс, шаффлборд, Братислава, бар, развлечения, турниры',
            'og:title' => 'Biliardovňa.sk — Бильярдный клуб в Братиславе',
            'og:description' => 'Крупнейший бильярдный клуб в Братиславе. Пирамида, Пул, Дартс, Шаффлборд и отличная атмосфера.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/home-ru.jpg',
        ],
        'uk' => [
            'title' => 'Biliardovňa.sk — Більярдний клуб у Братиславі',
            'description' => 'Найбільший більярдний клуб у Братиславі. Піраміда, Пул, Дартс, Шаффлборд та чудова атмосфера. Забронюйте стіл онлайн.',
            'keywords' => 'більярд, пул, піраміда, дартс, шаффлборд, Братислава, бар, розваги, турніри',
            'og:title' => 'Biliardovňa.sk — Більярдний клуб у Братиславі',
            'og:description' => 'Найбільший більярдний клуб у Братиславі. Піраміда, Пул, Дартс, Шаффлборд та чудова атмосфера.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/home-uk.jpg',
        ],
        'de' => [
            'title' => 'Biliardovňa.sk — Billardclub in Bratislava',
            'description' => 'Der größte Billardclub in Bratislava. Pyramide, Pool, Darts, Shuffleboard und tolle Atmosphäre. Buchen Sie einen Tisch online.',
            'keywords' => 'billard, pool, pyramide, darts, shuffleboard, Bratislava, bar, spaß, turniere',
            'og:title' => 'Biliardovňa.sk — Billardclub in Bratislava',
            'og:description' => 'Der größte Billardclub in Bratislava. Pyramide, Pool, Darts, Shuffleboard und tolle Atmosphäre.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/home-de.jpg',
        ],
    ],
    'games' => [
        'sk' => [
            'title' => 'Naše hry — Biliardovňa.sk',
            'description' => 'Ponúkame Ruskú pyramídu, Americký pool, Šípky a Shuffleboard. Profesionálne stoly a vybavenie.',
            'keywords' => 'hry, pyramída, pool, šípky, shuffleboard, vybavenie',
            'og:title' => 'Naše hry — Biliardovňa.sk',
            'og:description' => 'Ponúkame Ruskú pyramídu, Americký pool, Šípky a Shuffleboard. Profesionálne stoly a vybavenie.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/games-sk.jpg',
        ],
        'en' => [
            'title' => 'Our Games — Biliardovňa.sk',
            'description' => 'We offer Russian Pyramid, American Pool, Darts, and Shuffleboard. Professional tables and equipment.',
            'keywords' => 'games, pyramid, pool, darts, shuffleboard, equipment',
            'og:title' => 'Our Games — Biliardovňa.sk',
            'og:description' => 'We offer Russian Pyramid, American Pool, Darts, and Shuffleboard. Professional tables and equipment.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/games-en.jpg',
        ],
        'ru' => [
            'title' => 'Наши игры — Biliardovňa.sk',
            'description' => 'Мы предлагаем Русскую пирамиду, Американский пул, Дартс и Шаффлборд. Профессиональные столы и оборудование.',
            'keywords' => 'игры, пирамида, пул, дартс, шаффлборд, оборудование',
            'og:title' => 'Наши игры — Biliardovňa.sk',
            'og:description' => 'Мы предлагаем Русскую пирамиду, Американский пул, Дартс и Шаффлборд. Профессиональные столы и оборудование.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/games-ru.jpg',
        ],
        'uk' => [
            'title' => 'Наші ігри — Biliardovňa.sk',
            'description' => 'Ми пропонуємо Російську піраміду, Американський пул, Дартс та Шаффлборд. Професійні столи та обладнання.',
            'keywords' => 'ігри, піраміда, пул, дартс, шаффлборд, обладнання',
            'og:title' => 'Наші ігри — Biliardovňa.sk',
            'og:description' => 'Ми пропонуємо Російську піраміду, Американський пул, Дартс та Шаффлборд. Професійні столи та обладнання.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/games-uk.jpg',
        ],
        'de' => [
            'title' => 'Unsere Spiele — Biliardovňa.sk',
            'description' => 'Wir bieten Russische Pyramide, Amerikanisches Pool, Darts und Shuffleboard. Professionelle Tische und Ausrüstung.',
            'keywords' => 'spiele, pyramide, pool, darts, shuffleboard, ausrüstung',
            'og:title' => 'Unsere Spiele — Biliardovňa.sk',
            'og:description' => 'Wir bieten Russische Pyramide, Amerikanisches Pool, Darts und Shuffleboard. Professionelle Tische und Ausrüstung.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/games-de.jpg',
        ],
    ],
    'pricing' => [
        'sk' => [
            'title' => 'Cenník — Biliardovňa.sk',
            'description' => 'Cenník pre biliard, šípky a ostatné hry. Ponúkame výhodné ceny pre členov klubu a študentov.',
            'keywords' => 'cenník, cena, biliard, pool, zľavy, akcie',
            'og:title' => 'Cenník — Biliardovňa.sk',
            'og:description' => 'Cenník pre biliard, šípky a ostatné hry. Pozrite si naše ceny a rezervujte stôl.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/pricing-sk.jpg',
        ],
        'en' => [
            'title' => 'Pricing — Biliardovňa.sk',
            'description' => 'Price list for billiards, darts and other games. We offer great prices for club members and students.',
            'keywords' => 'pricing, price, billiard, pool, discounts, deals',
            'og:title' => 'Pricing — Biliardovňa.sk',
            'og:description' => 'Price list for billiards, darts and other games. Check our prices and book a table.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/pricing-en.jpg',
        ],
        'ru' => [
            'title' => 'Цены — Biliardovňa.sk',
            'description' => 'Прайс-лист на бильярд, дартс и другие игры. Предлагаем выгодные цены для членов клуба и студентов.',
            'keywords' => 'цены, прайс, бильярд, пул, скидки, акции',
            'og:title' => 'Цены — Biliardovňa.sk',
            'og:description' => 'Прайс-лист на бильярд, дартс и другие игры. Посмотрите наши цены и забронируйте стол.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/pricing-ru.jpg',
        ],
        'uk' => [
            'title' => 'Ціни — Biliardovňa.sk',
            'description' => 'Прайс-лист на більярд, дартс та інші ігри. Пропонуємо вигідні ціни для членів клубу та студентів.',
            'keywords' => 'ціни, прайс, більярд, пул, знижки, акції',
            'og:title' => 'Ціни — Biliardovňa.sk',
            'og:description' => 'Прайс-лист на більярд, дартс та інші ігри. Подивіться наші ціни та забронюйте стіл.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/pricing-uk.jpg',
        ],
        'de' => [
            'title' => 'Preise — Biliardovňa.sk',
            'description' => 'Preisliste für Billard, Darts und andere Spiele. Wir bieten günstige Preise für Clubmitglieder und Studenten.',
            'keywords' => 'preise, preisliste, billard, pool, rabatte, angebote',
            'og:title' => 'Preise — Biliardovňa.sk',
            'og:description' => 'Preisliste für Billard, Darts und andere Spiele. Sehen Sie sich unsere Preise an und buchen Sie einen Tisch.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/pricing-de.jpg',
        ],
    ],
    'deals' => [
        'sk' => [
            'title' => 'Akcie — Biliardovňa.sk',
            'description' => 'Aktuálne akcie, zľavy a špeciálne ponuky v našom klube. Nenechajte si ujsť skvelé príležitosti.',
            'keywords' => 'akcie, zľavy, ponuky, špeciálne, kupóny',
            'og:title' => 'Akcie — Biliardovňa.sk',
            'og:description' => 'Aktuálne akcie, zľavy a špeciálne ponuky v našom klube.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/deals-sk.jpg',
        ],
        'en' => [
            'title' => 'Deals — Biliardovňa.sk',
            'description' => 'Current deals, discounts and special offers in our club. Don\'t miss out on great opportunities.',
            'keywords' => 'deals, discounts, offers, specials, coupons',
            'og:title' => 'Deals — Biliardovňa.sk',
            'og:description' => 'Current deals, discounts and special offers in our club.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/deals-en.jpg',
        ],
        'ru' => [
            'title' => 'Акции — Biliardovňa.sk',
            'description' => 'Текущие акции, скидки и специальные предложения в нашем клубе. Не упустите отличные возможности.',
            'keywords' => 'акции, скидки, предложения, спецпредложения, купоны',
            'og:title' => 'Акции — Biliardovňa.sk',
            'og:description' => 'Текущие акции, скидки и специальные предложения в нашем клубе.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/deals-ru.jpg',
        ],
        'uk' => [
            'title' => 'Акції — Biliardovňa.sk',
            'description' => 'Поточні акції, знижки та спеціальні пропозиції в нашому клубі. Не пропустіть чудові можливості.',
            'keywords' => 'акції, знижки, пропозиції, спецпропозиції, купони',
            'og:title' => 'Акції — Biliardovňa.sk',
            'og:description' => 'Поточні акції, знижки та спеціальні пропозиції в нашому клубі.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/deals-uk.jpg',
        ],
        'de' => [
            'title' => 'Angebote — Biliardovňa.sk',
            'description' => 'Aktuelle Angebote, Rabatte und Sonderaktionen in unserem Club. Verpassen Sie keine großartigen Gelegenheiten.',
            'keywords' => 'angebote, rabatte, aktionen, specials, gutscheine',
            'og:title' => 'Angebote — Biliardovňa.sk',
            'og:description' => 'Aktuelle Angebote, Rabatte und Sonderaktionen in unserem Club.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/deals-de.jpg',
        ],
    ],
    'cafe' => [
        'sk' => [
            'title' => 'Kaviareň — Biliardovňa.sk',
            'description' => 'Relax v našej kaviarni. Široký výber nápojov a občerstvenia pre hráčov.',
            'keywords' => 'kaviareň, bar, nápoje, občerstvenie, káva',
            'og:title' => 'Kaviareň — Biliardovňa.sk',
            'og:description' => 'Relax v našej kaviarni. Široký výber nápojov a občerstvenia pre hráčov.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/cafe-sk.jpg',
        ],
        'en' => [
            'title' => 'Cafe — Biliardovňa.sk',
            'description' => 'Relax in our cafe. Wide selection of drinks and snacks for players.',
            'keywords' => 'cafe, bar, drinks, snacks, coffee',
            'og:title' => 'Cafe — Biliardovňa.sk',
            'og:description' => 'Relax in our cafe. Wide selection of drinks and snacks for players.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/cafe-en.jpg',
        ],
        'ru' => [
            'title' => 'Кафе — Biliardovňa.sk',
            'description' => 'Отдых в нашем кафе. Широкий выбор напитков и закусок для игроков.',
            'keywords' => 'кафе, бар, напитки, закуски, кофе',
            'og:title' => 'Кафе — Biliardovňa.sk',
            'og:description' => 'Отдых в нашем кафе. Широкий выбор напитков и закусок для игроков.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/cafe-ru.jpg',
        ],
        'uk' => [
            'title' => 'Кафе — Biliardovňa.sk',
            'description' => 'Відпочинок у нашому кафе. Широкий вибір напоїв та закусок для гравців.',
            'keywords' => 'кафе, бар, напої, закуски, кава',
            'og:title' => 'Кафе — Biliardovňa.sk',
            'og:description' => 'Відпочинок у нашому кафе. Широкий вибір напоїв та закусок для гравців.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/cafe-uk.jpg',
        ],
        'de' => [
            'title' => 'Café — Biliardovňa.sk',
            'description' => 'Entspannen Sie in unserem Café. Große Auswahl an Getränken und Snacks für Spieler.',
            'keywords' => 'café, bar, getränke, snacks, kaffee',
            'og:title' => 'Café — Biliardovňa.sk',
            'og:description' => 'Entspannen Sie in unserem Café. Große Auswahl an Getränken und Snacks für Spieler.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/cafe-de.jpg',
        ],
    ],
    'contact' => [
        'sk' => [
            'title' => 'Kontakt — Biliardovňa.sk',
            'description' => 'Kde nás nájdete? Adresa, mapa, telefón a otváracie hodiny. Tešíme sa na vašu návštevu.',
            'keywords' => 'kontakt, adresa, mapa, telefón, otváracie hodiny',
            'og:title' => 'Kontakt — Biliardovňa.sk',
            'og:description' => 'Kde nás nájdete? Adresa, mapa, telefón a otváracie hodiny.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/contact-sk.jpg',
        ],
        'en' => [
            'title' => 'Contact — Biliardovňa.sk',
            'description' => 'Where to find us? Address, map, phone and opening hours. We look forward to your visit.',
            'keywords' => 'contact, address, map, phone, opening hours',
            'og:title' => 'Contact — Biliardovňa.sk',
            'og:description' => 'Where to find us? Address, map, phone and opening hours.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/contact-en.jpg',
        ],
        'ru' => [
            'title' => 'Контакты — Biliardovňa.sk',
            'description' => 'Где нас найти? Адрес, карта, телефон и часы работы. Ждем вас в гости.',
            'keywords' => 'контакты, адрес, карта, телефон, часы работы',
            'og:title' => 'Контакты — Biliardovňa.sk',
            'og:description' => 'Где нас найти? Адрес, карта, телефон и часы работы.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/contact-ru.jpg',
        ],
        'uk' => [
            'title' => 'Контакти — Biliardovňa.sk',
            'description' => 'Де нас знайти? Адреса, карта, телефон та години роботи. Чекаємо на вас.',
            'keywords' => 'контакти, адреса, карта, телефон, години роботи',
            'og:title' => 'Контакти — Biliardovňa.sk',
            'og:description' => 'Де нас знайти? Адреса, карта, телефон та години роботи.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/contact-uk.jpg',
        ],
        'de' => [
            'title' => 'Kontakt — Biliardovňa.sk',
            'description' => 'Wo finden Sie uns? Adresse, Karte, Telefon und Öffnungszeiten. Wir freuen uns auf Ihren Besuch.',
            'keywords' => 'kontakt, adresse, karte, telefon, öffnungszeiten',
            'og:title' => 'Kontakt — Biliardovňa.sk',
            'og:description' => 'Wo finden Sie uns? Adresse, Karte, Telefon und Öffnungszeiten.',
            'og:type' => 'website',
            'og:image' => '/public/images/og/contact-de.jpg',
        ],
    ],
    'privacy' => [
        'sk' => [
            'title' => 'Ochrana osobných údajov — Biliardovňa.sk',
            'description' => 'Informácie o spracúvaní osobných údajov a používaní cookies podľa GDPR.',
            'keywords' => 'gdpr, ochrana údajov, súkromie, cookies',
            'og:title' => 'Ochrana osobných údajov — Biliardovňa.sk',
            'og:description' => 'Informácie o spracúvaní osobných údajov a používaní cookies podľa GDPR.',
            'og:type' => 'article',
            'og:image' => '/public/images/og/privacy-sk.jpg',
        ],
        'en' => [
            'title' => 'Privacy Policy — Biliardovňa.sk',
            'description' => 'Information about personal data processing and cookie usage according to GDPR.',
            'keywords' => 'gdpr, data protection, privacy, cookies',
            'og:title' => 'Privacy Policy — Biliardovňa.sk',
            'og:description' => 'Information about personal data processing and cookie usage according to GDPR.',
            'og:type' => 'article',
            'og:image' => '/public/images/og/privacy-en.jpg',
        ],
        'ru' => [
            'title' => 'Политика конфиденциальности — Biliardovňa.sk',
            'description' => 'Информация об обработке персональных данных и использовании файлов cookie в соответствии с GDPR.',
            'keywords' => 'gdpr, защита данных, конфиденциальность, cookies',
            'og:title' => 'Политика конфиденциальности — Biliardovňa.sk',
            'og:description' => 'Информация об обработке персональных данных и использовании файлов cookie в соответствии с GDPR.',
            'og:type' => 'article',
            'og:image' => '/public/images/og/privacy-ru.jpg',
        ],
        'uk' => [
            'title' => 'Політика конфіденційності — Biliardovňa.sk',
            'description' => 'Інформація про обробку персональних даних та використання файлів cookie відповідно до GDPR.',
            'keywords' => 'gdpr, захист даних, конфіденційність, cookies',
            'og:title' => 'Політика конфіденційності — Biliardovňa.sk',
            'og:description' => 'Інформація про обробку персональних даних та використання файлів cookie відповідно до GDPR.',
            'og:type' => 'article',
            'og:image' => '/public/images/og/privacy-uk.jpg',
        ],
        'de' => [
            'title' => 'Datenschutzerklärung — Biliardovňa.sk',
            'description' => 'Informationen zur Verarbeitung personenbezogener Daten und zur Verwendung von Cookies gemäß DSGVO.',
            'keywords' => 'dsgvo, datenschutz, privatsphäre, cookies',
            'og:title' => 'Datenschutzerklärung — Biliardovňa.sk',
            'og:description' => 'Informationen zur Verarbeitung personenbezogener Daten und zur Verwendung von Cookies gemäß DSGVO.',
            'og:type' => 'article',
            'og:image' => '/public/images/og/privacy-de.jpg',
        ],
    ],
    'terms' => [
        'sk' => [
            'title' => 'Všeobecné obchodné podmienky — Biliardovňa.sk',
            'description' => 'Pravidlá klubu a podmienky poskytovania služieb.',
            'keywords' => 'vop, podmienky, pravidlá, klubový poriadok',
            'og:title' => 'Všeobecné obchodné podmienky — Biliardovňa.sk',
            'og:description' => 'Pravidlá klubu a podmienky poskytovania služieb.',
            'og:type' => 'article',
            'og:image' => '/public/images/og/terms-sk.jpg',
        ],
        'en' => [
            'title' => 'Terms and Conditions — Biliardovňa.sk',
            'description' => 'Club rules and terms of service.',
            'keywords' => 'terms, conditions, rules, club policy',
            'og:title' => 'Terms and Conditions — Biliardovňa.sk',
            'og:description' => 'Club rules and terms of service.',
            'og:type' => 'article',
            'og:image' => '/public/images/og/terms-en.jpg',
        ],
        'ru' => [
            'title' => 'Правила и условия — Biliardovňa.sk',
            'description' => 'Правила клуба и условия предоставления услуг.',
            'keywords' => 'условия, правила, политика клуба',
            'og:title' => 'Правила и условия — Biliardovňa.sk',
            'og:description' => 'Правила клуба и условия предоставления услуг.',
            'og:type' => 'article',
            'og:image' => '/public/images/og/terms-ru.jpg',
        ],
        'uk' => [
            'title' => 'Правила та умови — Biliardovňa.sk',
            'description' => 'Правила клубу та умови надання послуг.',
            'keywords' => 'умови, правила, політика клубу',
            'og:title' => 'Правила та умови — Biliardovňa.sk',
            'og:description' => 'Правила клубу та умови надання послуг.',
            'og:type' => 'article',
            'og:image' => '/public/images/og/terms-uk.jpg',
        ],
        'de' => [
            'title' => 'Allgemeine Geschäftsbedingungen — Biliardovňa.sk',
            'description' => 'Clubregeln und Nutzungsbedingungen.',
            'keywords' => 'agb, bedingungen, regeln, clubordnung',
            'og:title' => 'Allgemeine Geschäftsbedingungen — Biliardovňa.sk',
            'og:description' => 'Clubregeln und Nutzungsbedingungen.',
            'og:type' => 'article',
            'og:image' => '/public/images/og/terms-de.jpg',
        ],
    ],
];
